services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - server
      - client
    networks:
      - tumble_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tumble
      POSTGRES_PASSWORD: tumble_pass
      POSTGRES_DB: tumble
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tumble"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tumble_network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tumble_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: tumble
      DB_PASSWORD: tumble_pass
      DB_NAME: tumble
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      FRONTEND_URL: http://localhost:3005
      LOG_LEVEL: DEBUG
      LOG_FORMAT: text
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tumble_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      API_URL: http://server:8080
      AUTH_SECRET: qG8/yMqJJGb4MJrf4sR1RWpjOTottFOr1SajSgeCmD0=
      NEXTAUTH_SECRET: qG8/yMqJJGb4MJrf4sR1RWpjOTottFOr1SajSgeCmD0=
      NEXTAUTH_URL: http://192.168.0.201:3005
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
    depends_on:
      - server
    networks:
      - tumble_network

volumes:
  postgres_data:
  redis_data:

networks:
  tumble_network:
    driver: bridge